/**
 * Button CSS Recipe — Vanilla Extract
 *
 * Uses themeVars (flat CSS variable names) generated by themes.ts.
 * This file is consumed by the Button component.
 *
 * Dual-mode:
 *   - styled (default): applies all theme vars, full styled appearance
 *   - unstyled: all vars removed, user controls everything
 */

import { recipe, RecipeVariants } from '@vanilla-extract/recipes';
import { themeVars } from '../theme';

// ── Base button ────────────────────────────────────────────────────────────

const buttonBase = {
  display:          'inline-flex' as const,
  alignItems:       'center' as const,
  justifyContent:   'center' as const,
  gap:              '6px' as const,
  fontFamily:       themeVars['font-family-sans'],
  fontWeight:       themeVars['button-font-weight'],
  lineHeight:       '1' as const,
  cursor:           'pointer' as const,
  border:           'none' as const,
  outline:          'none' as const,
  textDecoration:   'none' as const,
  userSelect:       'none' as const,
  whiteSpace:       'nowrap' as const,
  transition:       `background-color ${themeVars['motion-duration-fast']} ${themeVars['motion-easing-out']}, color ${themeVars['motion-duration-fast']} ${themeVars['motion-easing-out']}, box-shadow ${themeVars['motion-duration-fast']} ${themeVars['motion-easing-out']}, opacity ${themeVars['motion-duration-fast']} ${themeVars['motion-easing-out']}`,
  position:         'relative' as const,
  verticalAlign:    'middle' as const,

  ':focus-visible': {
    boxShadow: `0 0 0 3px ${themeVars['color-primary']}30`,
    outline:   'none' as const,
  },

  ':disabled': {
    opacity:    '0.44' as const,
    cursor:     'not-allowed' as const,
    pointerEvents: 'none' as const,
  },
};

// ── Unstyled variant (headless) ────────────────────────────────────────────

const buttonUnstyled = {
  all:              'unset' as const,
  display:          'inline-flex' as const,
  alignItems:       'center' as const,
  justifyContent:   'center' as const,
  gap:              '6px' as const,
  fontFamily:       themeVars['font-family-sans'],
  fontWeight:       themeVars['button-font-weight'],
  cursor:           'pointer' as const,
  userSelect:       'none' as const,
  whiteSpace:       'nowrap' as const,
  verticalAlign:    'middle' as const,
};

// ── Recipe definition ─────────────────────────────────────────────────────

export const button = recipe({
  variants: {
    /** Visual style of the button */
    variant: {
      solid:   { backgroundColor: themeVars['color-primary'],          color: themeVars['color-primary-fg'] },
      outline: { backgroundColor: 'transparent',                      color: themeVars['color-primary'],          border: `1.5px solid ${themeVars['color-primary']}` },
      ghost:   { backgroundColor: 'transparent',                      color: themeVars['color-text-primary'] },
      subtle:  { backgroundColor: `${themeVars['color-primary']}15`,  color: themeVars['color-primary'] },
    },

    /** Color scheme */
    colorScheme: {
      primary:   {},
      secondary: {},
      danger:    {},
      success:   {},
      warning:   {},
      info:      {},
      purple:    {},
      pink:      {},
    },

    /** Size */
    size: {
      xs: {
        height:     themeVars['button-height-xs'],
        padding:    themeVars['button-padding-xs'],
        fontSize:   themeVars['button-font-size-xs'],
        borderRadius: themeVars['button-radius-xs'],
      },
      sm: {
        height:     themeVars['button-height-sm'],
        padding:    themeVars['button-padding-sm'],
        fontSize:   themeVars['button-font-size-sm'],
        borderRadius: themeVars['button-radius-sm'],
      },
      md: {
        height:     themeVars['button-height-md'],
        padding:    themeVars['button-padding-md'],
        fontSize:   themeVars['button-font-size-md'],
        borderRadius: themeVars['button-radius-md'],
      },
      lg: {
        height:     themeVars['button-height-lg'],
        padding:    themeVars['button-padding-lg'],
        fontSize:   themeVars['button-font-size-lg'],
        borderRadius: themeVars['button-radius-lg'],
      },
      xl: {
        height:     themeVars['button-height-xl'],
        padding:    themeVars['button-padding-xl'],
        fontSize:   themeVars['button-font-size-lg'],
        borderRadius: themeVars['button-radius-lg'],
      },
    },

    /** Full width */
    fullWidth: {
      true:  { width: '100%' as const },
      false: {},
    },

    /** Pill / rounded */
    rounded: {
      true:  { borderRadius: themeVars['button-radius-full'] },
      false: {},
    },

    /** Loading state */
    loading: {
      true:  { opacity: '0.72' as const, cursor: 'wait' as const, pointerEvents: 'none' as const },
      false: {},
    },
  },

  compoundVariants: [
    // Solid × color scheme
    { variants: { variant: 'solid', colorScheme: 'primary'   }, style: { backgroundColor: themeVars['color-primary'],     color: themeVars['color-primary-fg']   } },
    { variants: { variant: 'solid', colorScheme: 'secondary' }, style: { backgroundColor: themeVars['color-secondary'],  color: themeVars['color-secondary-fg']  } },
    { variants: { variant: 'solid', colorScheme: 'danger'    }, style: { backgroundColor: themeVars['color-danger'],     color: '#ffffff'                       } },
    { variants: { variant: 'solid', colorScheme: 'success'   }, style: { backgroundColor: themeVars['color-success'],    color: '#ffffff'                       } },
    { variants: { variant: 'solid', colorScheme: 'warning'   }, style: { backgroundColor: themeVars['color-warning'],    color: themeVars['color-warning-fg']   } },
    { variants: { variant: 'solid', colorScheme: 'info'      }, style: { backgroundColor: themeVars['color-info'],       color: '#ffffff'                       } },
    { variants: { variant: 'solid', colorScheme: 'purple'    }, style: { backgroundColor: themeVars['color-purple'],    color: '#ffffff'                       } },
    { variants: { variant: 'solid', colorScheme: 'pink'      }, style: { backgroundColor: themeVars['color-pink'],      color: '#ffffff'                       } },

    // Outline × color scheme
    { variants: { variant: 'outline', colorScheme: 'primary'   }, style: { backgroundColor: 'transparent', color: themeVars['color-primary'],      border: `1.5px solid ${themeVars['color-primary']}` } },
    { variants: { variant: 'outline', colorScheme: 'secondary' }, style: { backgroundColor: 'transparent', color: themeVars['color-text-primary'], border: `1.5px solid ${themeVars['color-border-strong']}` } },
    { variants: { variant: 'outline', colorScheme: 'danger'    }, style: { backgroundColor: 'transparent', color: themeVars['color-danger'],     border: `1.5px solid ${themeVars['color-danger']}` } },
    { variants: { variant: 'outline', colorScheme: 'success'   }, style: { backgroundColor: 'transparent', color: themeVars['color-success'],    border: `1.5px solid ${themeVars['color-success']}` } },
    { variants: { variant: 'outline', colorScheme: 'warning'   }, style: { backgroundColor: 'transparent', color: themeVars['color-warning'],    border: `1.5px solid ${themeVars['color-warning']}` } },
    { variants: { variant: 'outline', colorScheme: 'info'      }, style: { backgroundColor: 'transparent', color: themeVars['color-info'],       border: `1.5px solid ${themeVars['color-info']}` } },

    // Ghost × color scheme
    { variants: { variant: 'ghost', colorScheme: 'primary'   }, style: { color: themeVars['color-primary']   } },
    { variants: { variant: 'ghost', colorScheme: 'secondary' }, style: { color: themeVars['color-text-primary']  } },
    { variants: { variant: 'ghost', colorScheme: 'danger'    }, style: { color: themeVars['color-danger']    } },
    { variants: { variant: 'ghost', colorScheme: 'success'   }, style: { color: themeVars['color-success']    } },
    { variants: { variant: 'ghost', colorScheme: 'warning'   }, style: { color: themeVars['color-warning']    } },
    { variants: { variant: 'ghost', colorScheme: 'info'      }, style: { color: themeVars['color-info']       } },

    // Subtle × color scheme
    { variants: { variant: 'subtle', colorScheme: 'primary'   }, style: { backgroundColor: `${themeVars['color-primary']}15`, color: themeVars['color-primary']   } },
    { variants: { variant: 'subtle', colorScheme: 'secondary' }, style: { backgroundColor: themeVars['color-surface'],       color: themeVars['color-text-primary']  } },
    { variants: { variant: 'subtle', colorScheme: 'danger'    }, style: { backgroundColor: themeVars['color-danger-bg'],     color: themeVars['color-danger']        } },
    { variants: { variant: 'subtle', colorScheme: 'success'   }, style: { backgroundColor: themeVars['color-success-bg'],    color: themeVars['color-success']       } },
    { variants: { variant: 'subtle', colorScheme: 'warning'   }, style: { backgroundColor: themeVars['color-warning-bg'],    color: themeVars['color-warning']       } },
    { variants: { variant: 'subtle', colorScheme: 'info'      }, style: { backgroundColor: themeVars['color-info-bg'],       color: themeVars['color-info']           } },
  ],

  defaultVariants: {
    variant:     'solid',
    colorScheme: 'primary',
    size:        'md',
    fullWidth:   false,
    rounded:     false,
    loading:     false,
  },

  base: buttonBase,
});

export const buttonUnstyledRecipe = recipe({
  base: buttonUnstyled,
});

export type ButtonVariants = RecipeVariants<typeof button>;
